// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DirResolver is an autogenerated mock type for the DirResolver type
type DirResolver struct {
	mock.Mock
}

// ResolveMassifDir provides a mock function with given fields: tenantIdentityOrLocalPath
func (_m *DirResolver) ResolveMassifDir(tenantIdentityOrLocalPath string) (string, error) {
	ret := _m.Called(tenantIdentityOrLocalPath)

	if len(ret) == 0 {
		panic("no return value specified for ResolveMassifDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(tenantIdentityOrLocalPath)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tenantIdentityOrLocalPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tenantIdentityOrLocalPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResolveSealDir provides a mock function with given fields: tenantIdentityOrLocalPath
func (_m *DirResolver) ResolveSealDir(tenantIdentityOrLocalPath string) (string, error) {
	ret := _m.Called(tenantIdentityOrLocalPath)

	if len(ret) == 0 {
		panic("no return value specified for ResolveSealDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(tenantIdentityOrLocalPath)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tenantIdentityOrLocalPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tenantIdentityOrLocalPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDirResolver creates a new instance of DirResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDirResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *DirResolver {
	mock := &DirResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
