// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ParseIdentifyingSegment is an autogenerated mock type for the ParseIdentifyingSegment type
type ParseIdentifyingSegment struct {
	mock.Mock
}

// Execute provides a mock function with given fields: blobPath
func (_m *ParseIdentifyingSegment) Execute(blobPath string) (string, error) {
	ret := _m.Called(blobPath)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(blobPath)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(blobPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(blobPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewParseIdentifyingSegment creates a new instance of ParseIdentifyingSegment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParseIdentifyingSegment(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParseIdentifyingSegment {
	mock := &ParseIdentifyingSegment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
