// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	massifs "github.com/datatrails/go-datatrails-merklelog/massifs"
	mock "github.com/stretchr/testify/mock"
)

// VerifiedContextReader is an autogenerated mock type for the VerifiedContextReader type
type VerifiedContextReader struct {
	mock.Mock
}

// GetVerifiedContext provides a mock function with given fields: ctx, tenantIdentity, massifIndex, opts
func (_m *VerifiedContextReader) GetVerifiedContext(ctx context.Context, tenantIdentity string, massifIndex uint64, opts ...massifs.ReaderOption) (*massifs.VerifiedContext, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tenantIdentity, massifIndex)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifiedContext")
	}

	var r0 *massifs.VerifiedContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, ...massifs.ReaderOption) (*massifs.VerifiedContext, error)); ok {
		return rf(ctx, tenantIdentity, massifIndex, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, ...massifs.ReaderOption) *massifs.VerifiedContext); ok {
		r0 = rf(ctx, tenantIdentity, massifIndex, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*massifs.VerifiedContext)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint64, ...massifs.ReaderOption) error); ok {
		r1 = rf(ctx, tenantIdentity, massifIndex, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVerifiedContextReader creates a new instance of VerifiedContextReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifiedContextReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerifiedContextReader {
	mock := &VerifiedContextReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
